services:
  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - gamevault-network

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini-development:/usr/local/etc/php/php.ini
    networks:
      - gamevault-network

  db:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamevault
      MYSQL_USER: gamer
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - gamevault-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - gamevault-network

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - gamevault-network

  mailpit:
    image: axllent/mailpit
    ports:
      - "${MAILPIT_UI_PORT:-8025}:8025"
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
    networks:
      - gamevault-network

networks:
  gamevault-network:
    driver: bridge
